pkgs = [
  "bat",
  "btop",
  "docker",
  "docker-buildx",
  "docker-compose",
  "eza",
  "fish",
  "fuzzel",
  "fzf",
  "kitty",
  "mpd",
  "mpv",
  "neovim",
  "niri",
  "quickshell",
  "starship",
  "zellij",
  "zoxide",
  "zsh",
]

[services]
mpd = "--user mpd.service"
docker = "docker.service"

[home]
".bashrc" = "./bash/.bashrc"

[home.cache]

[home.config]
bat = "./bat/"
btop = "./btop/"
fish = "./fish/"
fuzzel = "./fuzzel/"
kitty = "./kitty/"
mpd = "./mpd/"
mpv = "./mpv/"
nvim = "./nvim/"
starship = "./starship/"
zellij = "./zellij/"

[home.share]

[home.state]
[home.state.applications]
"fix-mouse.desktop" = "./applications/fix-mouse.desktop"
"wl-mirror.desktop" = "./applications/wl-mirror.desktop"
