
-- require("jls").setup({
-- 	root_markers = {
-- 		"settings.gradle",
-- 		"settings.gradle.kts",
-- 		".git",
-- 	},
-- 	settings = {
-- 		java = {
-- 			classPath = {
-- 				"shared/build/classes/java/main",
-- 				"services/ship/build/classes/java/main",
-- 			},
-- 		},
-- 	},
-- })
