require("mini.bracketed").setup()
require("mini.cursorword").setup()
require("mini.extra").setup()
require("mini.move").setup()
require("mini.pairs").setup()
require("mini.splitjoin").setup()
require("mini.surround").setup()
require("mini.indentscope").setup()
