[core]
restore_state = true

[audio]
output = autoaudiosink

[mpd]
enabled = true
hostname = 127.0.0.1
port = 6600

[spotify]
enabled = true
client_id = YOUR_CLIENT_ID
client_secret = YOUR_CLIENT_SECRET
bitrate = 320
