set -g default-command "/usr/bin/fish"
set -g default-shell "/usr/bin/fish"
set -g default-terminal "xterm-kitty"
set -s set-clipboard on
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

set -g prefix M-x
unbind C-b
bind M-x send-prefix

set-option -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g escape-time 0

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

setw -g mode-keys vi
bind-key ö copy-mode

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind-key Tab display-popup -w 60% -h 50% -E "ti"

# PLUGIN
set -g @plugin "tmuxpack/tpack"

# THEME
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"

set -g status-position top
set -g status-left " "
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"


set -g @plugin "tmux-plugins/tmux-yank"

set -g @plugin 'b0o/tmux-autoreload'
set -g @tmux-autoreload-quiet 0

set -g @plugin "tmux-plugins/tmux-resurrect"

set -g @plugin "tmux-plugins/tmux-continuum"
set -g @continuum-restore 'on'



run "tpack init"
