backend = "glx";

# BLUR
blur: {
        method = "dual_kawase"; # Other common methods include "gaussian" or "kawase"
          strength = 1;          # Adjust the strength of the blur (higher value = more blur)
          background = true;     # Enable blur for window backgrounds
          background-frame = false; # Blur the window frame (usually not desired with rounded corners)
          background-fixed = false; # Use fixed blur strength
      }

blur-background = true;

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c", # Exclude GTK client-side decorations from blur
];

# OPACITY
opacity-rule = [];

# SHADOWS
shadow = true;
shadow-radius = 12;
shadow-opacity = 0.75;
shadow-offset-x = -15;
shadow-offset-y = -15;

# FADING
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 10;

# BORDERS
corner-radius = 5;

rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
];
