# STATIC
music_directory    "~/Music"

# DYNAMIC
# Execute following command before starting the service
# mkdir -p ~/.local/share/mpd/playlists
# systemctl --user enable --now mpd
log_file           "syslog"
db_file            "~/.local/share/mpd/database"
state_file         "~/.local/share/mpd/state"
playlist_directory "~/.local/share/mpd/playlists"
