require("config.globals")
require("config.options")
require("config.keymaps")
require("config.autocmds")
require("config.filetypes")
require("config.lazy")
require("config.diagnostics")
require("lsp")
