# set-option -g default-shell /usr/bin/fish
# set-option -g default-command /usr/bin/fish

set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

unbind-key |
unbind-key -
bind-key | split-window -h /usr/bin/fish
bind-key - split-window -v /usr/bin/fish

set-option -g mouse on
set-option -g base-index 1
set-window-option -g pane-base-index 1

set-option -g allow-passthrough on
